//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.13.0
//     from Assets/Scripts/MyInputMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/MyInputMap.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @MyInputMap: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @MyInputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MyInputMap"",
    ""maps"": [
        {
            ""name"": ""TestKey"",
            ""id"": ""8ca9678f-cd24-49a9-8918-26655b6bb298"",
            ""actions"": [
                {
                    ""name"": ""NextClip"",
                    ""type"": ""Button"",
                    ""id"": ""e8b9ef9f-b369-404a-a0f6-2b9576fb21d3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PreviousClip"",
                    ""type"": ""Button"",
                    ""id"": ""e5ed9eab-6556-4da6-92ce-6130aa8bed98"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rescale"",
                    ""type"": ""Value"",
                    ""id"": ""3e7145b5-a75b-40a0-a060-93441f5a2f7b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Adjust"",
                    ""type"": ""Value"",
                    ""id"": ""eb0fa8fa-fc16-4eef-9eef-6fd966fa9c09"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NextVariable"",
                    ""type"": ""Button"",
                    ""id"": ""ba25cc76-9ce5-47fc-9d56-075d925b9da0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextScaleAdjust"",
                    ""type"": ""Button"",
                    ""id"": ""a55fb272-9b6b-4926-98d9-7fb0777a2729"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SeeThroughToggle"",
                    ""type"": ""Button"",
                    ""id"": ""5cc0434c-29f6-448b-b073-c827864fb347"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EnvironmentToggle"",
                    ""type"": ""Button"",
                    ""id"": ""f200c483-0b93-4f87-92ee-8cd46af94747"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ResetRecord"",
                    ""type"": ""Button"",
                    ""id"": ""ed126be2-e7b1-4978-9e21-05bea02dd4c5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BoardToggle"",
                    ""type"": ""Button"",
                    ""id"": ""54d093c2-98fc-4775-b81d-da5ff558c0f4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SavePrefs"",
                    ""type"": ""Button"",
                    ""id"": ""be941bf1-227c-47da-a828-f85f06e024eb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaceY"",
                    ""type"": ""Value"",
                    ""id"": ""7ac54c3a-c6f4-4cda-8744-d324fc877731"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7f68cb09-d990-47b2-8d7b-3e6504d06472"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextClip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c40feacc-792c-4b68-af11-5eaee1065032"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextClip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de60a219-7527-40f1-b8c6-5be29305eab8"",
                    ""path"": ""<XRController>{RightHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PreviousClip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""afa01b16-4a41-4695-bbf4-a72deb938bbd"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PreviousClip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""6889d095-c900-4d52-8aaf-80f0510458b0"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rescale"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""e1c68257-5043-47c3-94e0-75226909857c"",
                    ""path"": ""<XRController>{RightHand}/{ThumbrestTouch}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rescale"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""fd324a85-b17e-41a8-acbd-677c4b7342ae"",
                    ""path"": ""<XRController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rescale"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""8ea673c6-6418-4599-8b0a-9c5f465ec721"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rescale"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""c07b4198-e3ea-4a36-a560-9c32c3658491"",
                    ""path"": ""<XRController>{RightHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rescale"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""4bb3f656-8cad-4ae3-90b3-e113992777a7"",
                    ""path"": ""<XRController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rescale"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""08779004-3d7e-4f09-86fd-8ac7e194f715"",
                    ""path"": ""<XRController>{LeftHand}/{Primary2DAxis}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Adjust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8631c81-ac1b-4be1-825d-1039ae41a007"",
                    ""path"": ""<XRController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Adjust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d17154fa-42bd-4573-8782-d13cb5114772"",
                    ""path"": ""<XRController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Adjust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""b58eceb4-c4a6-4a35-85f9-69a6389aba1d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Adjust"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""cf21904c-9dfb-4314-b2cd-4fd051064d6a"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Adjust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3dc28c34-4a32-4ecf-8e92-1489f1d5dbb0"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Adjust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2fc54023-4889-4d0f-bb95-0f9c680b96ea"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Adjust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""40b2aab6-3e3d-4331-9ee1-4f573ff0fa23"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Adjust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4ababe27-362f-471b-8361-afeeb7afb4eb"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SeeThroughToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0995f24-1a77-45b5-860d-cb68ce1d3c32"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SeeThroughToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""e7eed143-58ce-47c2-a33e-a8cf1efaa4b9"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SeeThroughToggle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""945f3c1b-4fae-4b55-b250-bfdbf0fa6626"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryTrigger}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SeeThroughToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""4593f3b6-cd9b-4448-a8cb-ace19bb6e1d0"",
                    ""path"": ""<XRController>{RightHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SeeThroughToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6a5012d3-a97c-424d-bba6-f382a4f89e67"",
                    ""path"": ""<XRController>{LeftHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextVariable"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16015db4-0fba-427a-ac40-bfecf7fee3fa"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextVariable"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8da6bba-12a7-4b8b-b8bc-05ae9cdf32fd"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnvironmentToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""ecd57831-7922-4054-99df-945cf77eb736"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnvironmentToggle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""0425850a-911d-43eb-b5f3-46b6909756bc"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryTrigger}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnvironmentToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""1efdaf68-f324-4b38-8d43-94fc257dde6f"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnvironmentToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1f34446a-646d-4ebc-aa59-924744d50994"",
                    ""path"": ""<XRController>{LeftHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextScaleAdjust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92d82ca7-d37b-4f66-b01b-b4a028668aa7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextScaleAdjust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5daa82f-1561-4ba9-aa97-b57adb0429a4"",
                    ""path"": ""<XRController>{LeftHand}/{ThumbrestTouch}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetRecord"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75964176-3038-4475-ba0c-c8dbf9376997"",
                    ""path"": ""<XRController>{LeftHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetRecord"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""94e2775c-9d31-404c-981d-4919975dfdb1"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BoardToggle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""09e29b1f-0c67-4864-a1a3-2e54d234d8ce"",
                    ""path"": ""*/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BoardToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""dc8ddd87-992b-4c8c-a256-c36301505be0"",
                    ""path"": ""*/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BoardToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b29fc0d5-4918-435a-9d22-25494b7a06d8"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BoardToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""48cf6b85-2f44-44c2-aff1-cb3519fe1fbe"",
                    ""path"": ""<XRController>{LeftHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SavePrefs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""10e635fb-7691-4453-ac93-ad7f1c322c79"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceY"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""5a0754eb-247f-4b7c-b1a8-a0439a812ce5"",
                    ""path"": ""*/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""d753cdc7-be7c-4948-b03a-318c11b483a2"",
                    ""path"": ""<XRController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Gameplay"",
            ""id"": ""26c5aeff-bb09-47e8-a254-d8b96f5ae490"",
            ""actions"": [
                {
                    ""name"": ""AnyInput"",
                    ""type"": ""Button"",
                    ""id"": ""b82353de-a368-4675-ace6-38f367bf2b5f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""74f43de7-ee42-489d-9c11-c96c1c3c0ee8"",
                    ""path"": ""*/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnyInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TestKey
        m_TestKey = asset.FindActionMap("TestKey", throwIfNotFound: true);
        m_TestKey_NextClip = m_TestKey.FindAction("NextClip", throwIfNotFound: true);
        m_TestKey_PreviousClip = m_TestKey.FindAction("PreviousClip", throwIfNotFound: true);
        m_TestKey_Rescale = m_TestKey.FindAction("Rescale", throwIfNotFound: true);
        m_TestKey_Adjust = m_TestKey.FindAction("Adjust", throwIfNotFound: true);
        m_TestKey_NextVariable = m_TestKey.FindAction("NextVariable", throwIfNotFound: true);
        m_TestKey_NextScaleAdjust = m_TestKey.FindAction("NextScaleAdjust", throwIfNotFound: true);
        m_TestKey_SeeThroughToggle = m_TestKey.FindAction("SeeThroughToggle", throwIfNotFound: true);
        m_TestKey_EnvironmentToggle = m_TestKey.FindAction("EnvironmentToggle", throwIfNotFound: true);
        m_TestKey_ResetRecord = m_TestKey.FindAction("ResetRecord", throwIfNotFound: true);
        m_TestKey_BoardToggle = m_TestKey.FindAction("BoardToggle", throwIfNotFound: true);
        m_TestKey_SavePrefs = m_TestKey.FindAction("SavePrefs", throwIfNotFound: true);
        m_TestKey_PlaceY = m_TestKey.FindAction("PlaceY", throwIfNotFound: true);
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_AnyInput = m_Gameplay.FindAction("AnyInput", throwIfNotFound: true);
    }

    ~@MyInputMap()
    {
        UnityEngine.Debug.Assert(!m_TestKey.enabled, "This will cause a leak and performance issues, MyInputMap.TestKey.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Gameplay.enabled, "This will cause a leak and performance issues, MyInputMap.Gameplay.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TestKey
    private readonly InputActionMap m_TestKey;
    private List<ITestKeyActions> m_TestKeyActionsCallbackInterfaces = new List<ITestKeyActions>();
    private readonly InputAction m_TestKey_NextClip;
    private readonly InputAction m_TestKey_PreviousClip;
    private readonly InputAction m_TestKey_Rescale;
    private readonly InputAction m_TestKey_Adjust;
    private readonly InputAction m_TestKey_NextVariable;
    private readonly InputAction m_TestKey_NextScaleAdjust;
    private readonly InputAction m_TestKey_SeeThroughToggle;
    private readonly InputAction m_TestKey_EnvironmentToggle;
    private readonly InputAction m_TestKey_ResetRecord;
    private readonly InputAction m_TestKey_BoardToggle;
    private readonly InputAction m_TestKey_SavePrefs;
    private readonly InputAction m_TestKey_PlaceY;
    /// <summary>
    /// Provides access to input actions defined in input action map "TestKey".
    /// </summary>
    public struct TestKeyActions
    {
        private @MyInputMap m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public TestKeyActions(@MyInputMap wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "TestKey/NextClip".
        /// </summary>
        public InputAction @NextClip => m_Wrapper.m_TestKey_NextClip;
        /// <summary>
        /// Provides access to the underlying input action "TestKey/PreviousClip".
        /// </summary>
        public InputAction @PreviousClip => m_Wrapper.m_TestKey_PreviousClip;
        /// <summary>
        /// Provides access to the underlying input action "TestKey/Rescale".
        /// </summary>
        public InputAction @Rescale => m_Wrapper.m_TestKey_Rescale;
        /// <summary>
        /// Provides access to the underlying input action "TestKey/Adjust".
        /// </summary>
        public InputAction @Adjust => m_Wrapper.m_TestKey_Adjust;
        /// <summary>
        /// Provides access to the underlying input action "TestKey/NextVariable".
        /// </summary>
        public InputAction @NextVariable => m_Wrapper.m_TestKey_NextVariable;
        /// <summary>
        /// Provides access to the underlying input action "TestKey/NextScaleAdjust".
        /// </summary>
        public InputAction @NextScaleAdjust => m_Wrapper.m_TestKey_NextScaleAdjust;
        /// <summary>
        /// Provides access to the underlying input action "TestKey/SeeThroughToggle".
        /// </summary>
        public InputAction @SeeThroughToggle => m_Wrapper.m_TestKey_SeeThroughToggle;
        /// <summary>
        /// Provides access to the underlying input action "TestKey/EnvironmentToggle".
        /// </summary>
        public InputAction @EnvironmentToggle => m_Wrapper.m_TestKey_EnvironmentToggle;
        /// <summary>
        /// Provides access to the underlying input action "TestKey/ResetRecord".
        /// </summary>
        public InputAction @ResetRecord => m_Wrapper.m_TestKey_ResetRecord;
        /// <summary>
        /// Provides access to the underlying input action "TestKey/BoardToggle".
        /// </summary>
        public InputAction @BoardToggle => m_Wrapper.m_TestKey_BoardToggle;
        /// <summary>
        /// Provides access to the underlying input action "TestKey/SavePrefs".
        /// </summary>
        public InputAction @SavePrefs => m_Wrapper.m_TestKey_SavePrefs;
        /// <summary>
        /// Provides access to the underlying input action "TestKey/PlaceY".
        /// </summary>
        public InputAction @PlaceY => m_Wrapper.m_TestKey_PlaceY;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_TestKey; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="TestKeyActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(TestKeyActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="TestKeyActions" />
        public void AddCallbacks(ITestKeyActions instance)
        {
            if (instance == null || m_Wrapper.m_TestKeyActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TestKeyActionsCallbackInterfaces.Add(instance);
            @NextClip.started += instance.OnNextClip;
            @NextClip.performed += instance.OnNextClip;
            @NextClip.canceled += instance.OnNextClip;
            @PreviousClip.started += instance.OnPreviousClip;
            @PreviousClip.performed += instance.OnPreviousClip;
            @PreviousClip.canceled += instance.OnPreviousClip;
            @Rescale.started += instance.OnRescale;
            @Rescale.performed += instance.OnRescale;
            @Rescale.canceled += instance.OnRescale;
            @Adjust.started += instance.OnAdjust;
            @Adjust.performed += instance.OnAdjust;
            @Adjust.canceled += instance.OnAdjust;
            @NextVariable.started += instance.OnNextVariable;
            @NextVariable.performed += instance.OnNextVariable;
            @NextVariable.canceled += instance.OnNextVariable;
            @NextScaleAdjust.started += instance.OnNextScaleAdjust;
            @NextScaleAdjust.performed += instance.OnNextScaleAdjust;
            @NextScaleAdjust.canceled += instance.OnNextScaleAdjust;
            @SeeThroughToggle.started += instance.OnSeeThroughToggle;
            @SeeThroughToggle.performed += instance.OnSeeThroughToggle;
            @SeeThroughToggle.canceled += instance.OnSeeThroughToggle;
            @EnvironmentToggle.started += instance.OnEnvironmentToggle;
            @EnvironmentToggle.performed += instance.OnEnvironmentToggle;
            @EnvironmentToggle.canceled += instance.OnEnvironmentToggle;
            @ResetRecord.started += instance.OnResetRecord;
            @ResetRecord.performed += instance.OnResetRecord;
            @ResetRecord.canceled += instance.OnResetRecord;
            @BoardToggle.started += instance.OnBoardToggle;
            @BoardToggle.performed += instance.OnBoardToggle;
            @BoardToggle.canceled += instance.OnBoardToggle;
            @SavePrefs.started += instance.OnSavePrefs;
            @SavePrefs.performed += instance.OnSavePrefs;
            @SavePrefs.canceled += instance.OnSavePrefs;
            @PlaceY.started += instance.OnPlaceY;
            @PlaceY.performed += instance.OnPlaceY;
            @PlaceY.canceled += instance.OnPlaceY;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="TestKeyActions" />
        private void UnregisterCallbacks(ITestKeyActions instance)
        {
            @NextClip.started -= instance.OnNextClip;
            @NextClip.performed -= instance.OnNextClip;
            @NextClip.canceled -= instance.OnNextClip;
            @PreviousClip.started -= instance.OnPreviousClip;
            @PreviousClip.performed -= instance.OnPreviousClip;
            @PreviousClip.canceled -= instance.OnPreviousClip;
            @Rescale.started -= instance.OnRescale;
            @Rescale.performed -= instance.OnRescale;
            @Rescale.canceled -= instance.OnRescale;
            @Adjust.started -= instance.OnAdjust;
            @Adjust.performed -= instance.OnAdjust;
            @Adjust.canceled -= instance.OnAdjust;
            @NextVariable.started -= instance.OnNextVariable;
            @NextVariable.performed -= instance.OnNextVariable;
            @NextVariable.canceled -= instance.OnNextVariable;
            @NextScaleAdjust.started -= instance.OnNextScaleAdjust;
            @NextScaleAdjust.performed -= instance.OnNextScaleAdjust;
            @NextScaleAdjust.canceled -= instance.OnNextScaleAdjust;
            @SeeThroughToggle.started -= instance.OnSeeThroughToggle;
            @SeeThroughToggle.performed -= instance.OnSeeThroughToggle;
            @SeeThroughToggle.canceled -= instance.OnSeeThroughToggle;
            @EnvironmentToggle.started -= instance.OnEnvironmentToggle;
            @EnvironmentToggle.performed -= instance.OnEnvironmentToggle;
            @EnvironmentToggle.canceled -= instance.OnEnvironmentToggle;
            @ResetRecord.started -= instance.OnResetRecord;
            @ResetRecord.performed -= instance.OnResetRecord;
            @ResetRecord.canceled -= instance.OnResetRecord;
            @BoardToggle.started -= instance.OnBoardToggle;
            @BoardToggle.performed -= instance.OnBoardToggle;
            @BoardToggle.canceled -= instance.OnBoardToggle;
            @SavePrefs.started -= instance.OnSavePrefs;
            @SavePrefs.performed -= instance.OnSavePrefs;
            @SavePrefs.canceled -= instance.OnSavePrefs;
            @PlaceY.started -= instance.OnPlaceY;
            @PlaceY.performed -= instance.OnPlaceY;
            @PlaceY.canceled -= instance.OnPlaceY;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="TestKeyActions.UnregisterCallbacks(ITestKeyActions)" />.
        /// </summary>
        /// <seealso cref="TestKeyActions.UnregisterCallbacks(ITestKeyActions)" />
        public void RemoveCallbacks(ITestKeyActions instance)
        {
            if (m_Wrapper.m_TestKeyActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="TestKeyActions.AddCallbacks(ITestKeyActions)" />
        /// <seealso cref="TestKeyActions.RemoveCallbacks(ITestKeyActions)" />
        /// <seealso cref="TestKeyActions.UnregisterCallbacks(ITestKeyActions)" />
        public void SetCallbacks(ITestKeyActions instance)
        {
            foreach (var item in m_Wrapper.m_TestKeyActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TestKeyActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="TestKeyActions" /> instance referencing this action map.
    /// </summary>
    public TestKeyActions @TestKey => new TestKeyActions(this);

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_AnyInput;
    /// <summary>
    /// Provides access to input actions defined in input action map "Gameplay".
    /// </summary>
    public struct GameplayActions
    {
        private @MyInputMap m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public GameplayActions(@MyInputMap wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/AnyInput".
        /// </summary>
        public InputAction @AnyInput => m_Wrapper.m_Gameplay_AnyInput;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="GameplayActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="GameplayActions" />
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @AnyInput.started += instance.OnAnyInput;
            @AnyInput.performed += instance.OnAnyInput;
            @AnyInput.canceled += instance.OnAnyInput;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="GameplayActions" />
        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @AnyInput.started -= instance.OnAnyInput;
            @AnyInput.performed -= instance.OnAnyInput;
            @AnyInput.canceled -= instance.OnAnyInput;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GameplayActions.UnregisterCallbacks(IGameplayActions)" />.
        /// </summary>
        /// <seealso cref="GameplayActions.UnregisterCallbacks(IGameplayActions)" />
        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="GameplayActions.AddCallbacks(IGameplayActions)" />
        /// <seealso cref="GameplayActions.RemoveCallbacks(IGameplayActions)" />
        /// <seealso cref="GameplayActions.UnregisterCallbacks(IGameplayActions)" />
        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="GameplayActions" /> instance referencing this action map.
    /// </summary>
    public GameplayActions @Gameplay => new GameplayActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "TestKey" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="TestKeyActions.AddCallbacks(ITestKeyActions)" />
    /// <seealso cref="TestKeyActions.RemoveCallbacks(ITestKeyActions)" />
    public interface ITestKeyActions
    {
        /// <summary>
        /// Method invoked when associated input action "NextClip" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNextClip(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PreviousClip" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPreviousClip(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Rescale" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRescale(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Adjust" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAdjust(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NextVariable" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNextVariable(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NextScaleAdjust" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNextScaleAdjust(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SeeThroughToggle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSeeThroughToggle(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "EnvironmentToggle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEnvironmentToggle(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ResetRecord" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnResetRecord(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BoardToggle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBoardToggle(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SavePrefs" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSavePrefs(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PlaceY" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPlaceY(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Gameplay" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="GameplayActions.AddCallbacks(IGameplayActions)" />
    /// <seealso cref="GameplayActions.RemoveCallbacks(IGameplayActions)" />
    public interface IGameplayActions
    {
        /// <summary>
        /// Method invoked when associated input action "AnyInput" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAnyInput(InputAction.CallbackContext context);
    }
}
